name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/

  lint-markdown:
    name: Lint Markdown
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2

      - name: Lint markdown files
        run: markdownlint-cli2 "blog/**/*.md" "docs/**/*.md"

    continue-on-error: true

  test-html:
    name: Lint HTML
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build/

      - name: Install htmlhint
        run: npm install --save-dev htmlhint

      - name: Run htmlhint
        run: npx htmlhint build/
